### ISSUE TITLE
Add multi-account support

### ISSUE THREAD

**Issue by kamushadenes** [rosenpin/i3-agenda#35]
I would like to use this with my personal and work accounts, how can I do that?

**Comment by rosenpin** [comment]
Currently this script only supports a single account, you could add your work account calendar to your personal account calendar, then sync your personal calendar. This will make the script go through both calendars

**Comment by ungarida** [comment]
This is not going to be good enough workaround. In case of a Google Account managed by an organization you can share with your personal account only with permission to see busy / free events :disappointed:

**Comment by rosenpin** [comment]
we could add an option to provide the script with multiple credentials file (using the -c flag)  
This will require users to download 2 files, one for each account, then the script will simply fetch n times for each credentials file provided, it will then just merge the resulting lists and from there it's business as usual.  


### TODO:
1. Change the get_events call to be called for each credential file provided  
https://github.com/rosenpin/i3-agenda/blob/master/i3_agenda/__init__.py#L33

2. Add support for multiple credentials file command line argument
https://github.com/rosenpin/i3-agenda/blob/master/i3_agenda/config.py#L14

**Comment by rosenpin** [comment]
It's now possible since @notdodo [commit](https://github.com/rosenpin/i3-agenda/commit/ef5668a5d746210d78b397bd979ad568c29b1524)

Previously if you did it, both blocks would have pulled from the same cache.  
Now you can set a different config dir for each block and let them run simultaneously  

You would need something like this

### Step 1
You will have to create both directories first 
`mkdir -p ~/.config/i3agenda/work && mkdir -p ~/.config/i3agenda/personal`

### Step 2 
You will need to download both google credential files for both accounts and place them in the appropriate directories.  
[More information here](https://github.com/rosenpin/i3-agenda#google-api)

### Step 3 
Configure your bar  
Polybar example  

```
modules-center = agenda-personal agenda-work
....
[module/agenda-personal]
type = custom/script
; Show the next event and forget cache automatically every 60 minutes. Save cache in personal config dir
exec = i3-agenda -c ~/.config/i3agenda/personal/google_credentials.json -ttl 60 --conf ~/.config/i3agenda/personal
interval = 60
....

[module/agenda-work]
type = custom/script
; Show the next event and forget cache automatically every 60 minutes. Save cache in work config dir
exec = i3-agenda -c ~/.config/i3agenda/work/google_credentials.json -ttl 60 --conf ~/.config/i3agenda/work
interval = 60
```
